GEOUNED-org/GEOUNED

scripts/configReverse.ini, src/GEOReverse/Modules/MCNPinput.py, src/GEOReverse/Modules/XMLinput.py
I tried the reverse function and it took me a lot of time to find out why my output was empty. This error message will help users locate the reason.
=> Added Error messages for when no cells are selected

scripts/geouned, scripts/geouned.py, src/GEOReverse/Modules/MCNPinput.py, src/GEOReverse/Modules/XMLinput.py, src/GEOReverse/Modules/processInp.py, src/GEOUNED/LoadFile/LoadFunctions.py, src/GEOUNED/Utils/Functions.py, src/GEOUNED/__init__.py
Following up on PR #41 I found all the ```sys.exit()``` commands in the code and have replaced them with raise ValueError or FileNotFoundError. Same motivation as #41
=> raising catchable error instead of exit

.github/workflows/ci.yml, README.md
Just making this tiny PR to check that the CI is triggering as I didn't see it run on PR #52
=> typo correction to test if CI is working

src/geouned/GEOUNED/Conversion/CellDefinition.py
redoing pr #78 but this time merging to dev branch
=> redo commit bc74e7e

src/geouned/GEOUNED/Conversion/CellDefinition.py, src/geouned/GEOUNED/Cuboid/translate.py, src/geouned/GEOUNED/Decompose/Decom_one.py, src/geouned/GEOUNED/LoadFile/LoadFunctions.py, src/geouned/GEOUNED/LoadFile/LoadSTEP.py
I've been going through the files changing the variables to all be snake case to follow PEP8 guidlines
https://peps.python.org/pep-0008/#function-and-variable-names
I've done five files and plan to carry on with more later, but I think this PR can go ahead as a separate PR
Splitting the PR up as it is already a large diff
Apologies I snuck in a small change to the README.md by adding the badge for the python package action. The action badge should go green when we create the next release
=> Snake case variables (PR 1 of several)

src/geouned/GEOUNED/Conversion/CellDefinition.py, src/geouned/GEOUNED/Cuboid/translate.py, src/geouned/GEOUNED/Utils/BasicFunctions_part1.py, src/geouned/GEOUNED/Utils/BasicFunctions_part2.py, src/geouned/GEOUNED/Utils/Functions.py, src/geouned/GEOUNED/Utils/Geometry_GU.py, src/geouned/GEOUNED/Utils/booleanFunction.py
A few more variables have been changed to snake case
Pep8 recommends variables in lower case with _ to separate words
following on PR #98
=> Snake case variables (PR 2 of several) 

.github/pull_request_template.md
Wondering if it is worth throwing a PR template.
What do you think of the wording perhaps this could combine with your contribution guide @alexvalentine94
=> added draft template for consideration

tests/test_transport.py
removal of a duplicated import statement
=> duplicate import openmc

.github/ISSUE_TEMPLATE/feature_request.md, .github/ISSUE_TEMPLATE/improve_documentation.md, .github/workflows/enforce_main_pr_from_dev.yml
Addition of templates for new features and changes to documentation.
=> Add issue templates 

docs/install.rst, docs/methodology.rst
I've added a section to the documentations for developer install
=> Improving docs install section

README.md
This PR removes sections of the readme that are out of date or duplicate details in the online docs
=> removed duplication between readme and docs

README.md
Just a one liner PR that adds a live badge showing the latest pypi version
=> added pypi version badge

README.md
Tiny URL fix for the new badges. They now point to the correct URL endpoint
=> corrected badge urls

.github/workflows/documentation_release.yml, .github/workflows/documentation_update_dev.yml, docs/conf.py, docs/index.rst, docs/install/install_windows.rst, docs/version_switcher.json, pyproject.toml
This PR updates the documentation creating CI so that it builds docs with the Pydata theme.
Docs are built every PR and push as previously and this now gets put in the dev folder on the gh-pages branch
Docs are now built with every tag release and this gets put in a folder with the version number on the gh-pages branch
I've investigated 5 ways of adding versions to sphinx based docs and am convinced that the [pydata](https://pydata-sphinx-theme.readthedocs.io/en/stable/) is the best option currently and used by famous packages like [numpy](https://numpy.org/doc/stable/)
- https://github.com/Smile-SA/sphinx-versions no longer maintained does not work with latest sphinx
- https://github.com/Holzhaus/sphinx-multiversion no longer maintained does not work with latest sphinx
- …
=> Adding version support to docs

docs/usage/python_api_usage.rst
=> added missing " to docs example

docs/conf.py
tiny PR to fix the url used to find the document versions in the documentation
=> fixed versions url

docs/developer_guide.rst
adds some version info to the docs
=> added part from alex comment

docs/install/index.rst
Some additional guidance in the docs related to install requiring semantic versioning. 
#213
=> closes #213; additional guidance for install

src/geouned/GEOUNED/utils/boolean_function.py
Solve the problem when a sequence was append to a Boolsequence with boolean value.
=> Bug compsolid

src/geouned/GEOUNED/core.py
Fix bug when sort enclosure option is enabled (#254)
=> fix sort enclosure bug

src/geouned/GEOUNED/utils/data_classes.py
Reverts GEOUNED-org/GEOUNED#265
bad black formatted - format checks didn't pass
=> Revert "Update data_classes.py"

.github/workflows/documentation_release.yml, docs/developer_guide.rst, docs/install/index.rst, docs/usage/python_cadtocsg_api_usage.rst, docs/usage/python_cadtocsg_cli_usage.rst, src/geouned/GEOUNED/core.py, src/geouned/GEOUNED/utils/boolean_function.py, src/geouned/GEOUNED/utils/data_classes.py, src/geouned/GEOUNED/void/void.py, src/geouned/GEOUNED/void/void_box_class.py, src/geouned/GEOUNED/write/functions.py, tests/config_cadtocsg_complete_defaults.json, tests/config_cadtocsg_non_defaults.json, tests/test_cadtocsg.py
Update most recent bug fixed in the dev branch to the main branch
=> Update main branch

src/geouned/GEOUNED/decompose/decom_one.py, src/geouned/GEOUNED/utils/data_classes.py, src/geouned/GEOUNED/utils/geometry_gu.py
Add modifications to solve partially some problems with contigous toroidal face forming a closed surface. 
In order to fully solve the problem, original solid must be divide in smallest parts.
=> Torus envelope fix (partially)

index.html
Since documentation is going to be actively updated, it would be better to point to dev by default.
N.A.
- [x ] I'm making a PR from a feature branch on my fork into GEOUNED-org/GEOUNED/dev branch
- [x ] I have followed [PEP8 style guide]([url](https://peps.python.org/pep-0008/)) for Python or run a formatter such as [black]([url](https://github.com/psf/black)) or [ruff format]([url](https://github.com/astral-sh/ruff)) on my code
=> Update index.html to point to dev documentation

src/geouned/GEOUNED/decompose/decom_one.py
Fix small issue in additional plane function. Does not normalize vector if length in 0.
=> Miror torus

docs/example_of_use.rst, docs/index.rst
Adds an Example of Use to the documentation.
=> add how to use to the documentation

docs/version_switcher.json, src/geouned/GEOUNED/write/serpent_format.py
temporal patch to remove issue 309 on conda-forge Package
=> Update serpent_format.py (#310)
