GEOUNED-org/GEOUNED

src/GEOUNED/Write/Functions.py, src/GEOUNED/Write/SerpentFormat.py, src/GEOUNED/Write/WriteFiles.py, src/GEOUNED/__init__.py
Initial effort at also writing Serpent input files
Some testing success for simple models but needs further tests and edge cases.
Hopefully useful for this great tool :) 
Reverse reading of Serpent -> CAD in progress but will raise separate PR.
=> Capability to write to Serpent

src/GEOReverse/Modules/Parser/parser.py
fixes a dtype used before allocated error for extra data cards starting with "m".
Followed the existing pattern with none materials related cards (mphys) added to the if statement and material related (mx) card added a seperate dtype allocation.
There possibly should be a final else clause with dtype = None to catch any other data cards starting with m that are not dealt with already.
=> Update parser.py - fix for mphys and mx cards

src/GEOUNED/__init__.py
Dear all,
Thank you for developing this great conversion tool.
When debug=True, many output files are generated into a working directory, especially trying to convert large complicated geometries.
I was wondering whether I should point this out or not.
The output stp files might be better to export not into the current directory but into the sub directory to avoid.
Here I try a pull request.
Thank you for your attention.
Best Regards,
=> debug step files export to sub directory

src/GEOUNED/Cuboid/translate.py
For details see Issue  #33.
Removal of several unused imports and variables in `Cuboid>traslate.py`. Please check that these were not actually supposed to be used somewhere.
=> Removed unused imports and variables

src/GEOReverse/reverse.py
Hi
I was just reading the code and though this ```exit``` could be replaced with a ValueError.
This is useful as we can catch and therefore test these ValueErrors and the error message is more informative for the user as it lets them know what the acceptable options are.
All the best
Jon
=> Raise ValueError instead of exit()

testing/test.py
Hi,
While reading through the code I noticed this small change.
This would allow the test.py to work for other users as it adds the src folder by it's relative location to the test.py file instead of on a specific username.
=> Update to testing path

src/GEOReverse/__init__.py, src/GEOUNED/__init__.py
Thanks for reviewing and merging the last couple of PRs.
This one is another small minimal PR that would allow GEOUNED to work with the conda freecad package.
Conda freecad package provides compiled FreeCAD.so files, compiled to be compatible with the conda python.
The means we can make use of geouned with our system python :tada: instead of the ```FreeCAD.cmd``` command and also we can avoid manually appending paths to the sys :tada:.
The conda freecad package is distributed under the name ```freecad``` lower case and once imported it would add the path to the appropriately compile FreeCAD.so and then one can import FreeCAD and it know where to find the .so file.
If the ```try:``` fails then it will pass the except and therefore this has no impact on the other ways of running the …
=> added try except for compatibility conda freecad

.github/workflows/ci.yml, .gitignore, pyproject.toml, tests/test_convert.py
This PR adds minimal CI that installs the GEOUNED package and FreeCAD (using Conda). Then it converts all 52 the step files found in the testing/inputSTEPS folder and checks that an openmc and mcnp output file exist.
A combination of Python versions and operating systems are tested, this can be changed but for now I've gone with:
|             | Linux (Ubuntu) | Windows | Mac OS |
|-------------|----------------|---------|--------|
| Python 3.8  | tested         |         |        |
| Python 3.9  | tested         |         |        |
| Python 3.10 | tested         |         |        |
| Python 3.11 | tested         | tested  | tested |
If this PR is successful I can follow it up with some additional testing that checks the volumes of the resulting solids and checks that the resulting …
=> Adding minimal ci to check cad converts

.github/workflows/ci.yml, tests/test_volumes.py
This PR adds to the CI with some tests that check the volume of the CAD file and the volume of the resulting CSG file.
The tests can be run locally or on the CI. When run locally the volume tolerance is decreased and the number of samples is increased in the stochastic volume calculation.
There  were a few approaches that could have bee taken with this. I first made an implementation that did one stochastic volume calculation per model with a large bounding box over the whole model. While this worked I found it was quicker to do a stochastic volume calculation for every cell in every model. In this way the bound boxes were more compact around the solid and the stochastic  volume calculation was more efficient.
Several of the stp files have been removed from the volume calculation test. …
=> Adding minimal volume checking CI comparing CAD and CSG volumes

docs/examples.md, docs/index.md, docs/installation.md, docs/python_api.md, docs/theory_and_methodology.md, mkdocs.yml, pyproject.toml
Also needs a random function to show docstrings for
```
import typing
def csg_to_cad(
csg_filename: str,
csg_format: str,
output_filename: str,
bounding_box: typing.Tuple(float),
) -> str:
"""Converts a CSG geometry into a CAD geometry and saves a STEP file
Args:
csg_filename (str): the filename of the CSG file
csg_format (str): the format / Monte Carlo code of the CSG file.
Acceptable options are 'openmc', 'mcnp', 'serpent'
bounding_box (typing.Tuple): A bounding box for the geometry in the
format lower left x,y,z and upper right x,y,z
output_filename (str): the filename of the produced CAD file
Returns:
str: output file path of the CAD file produced
"""
return 'hello world'
def cad_to_csg(
cad_filename: str,
csg_format: str,
output_filename: str,
start_cell_id: int,
) -> str: …
```
=> Added mkdocs

.github/workflows/ci.yml, tests/cross_sections.xml, tests/test_transport.py
This PR adds another pytest test script.
This new test runs the produced openmc xml files with particle transport to check that the geometry is well defined and particles don't get lost. A source is defined to be sampled from within the bounding box so that particles appear all over the geometry and travel in isotropic directions.
While running these tests (with lots of particles) I noticed a few files had lost particles and I've therefore removed them from these tests. To track the bug that is causing these few conversions to fail I've raised[ an issue](https://github.com/GEOUNED-org/GEOUNED/issues/60) with a minimal example
I think this test is still worth merging as it adds some protection to the majority of conversions that do work. While we change the code it will be reassuring to …
=> Adding minimal particle transport tests on resulting csg files

src/GEOUNED/Write/OpenMCFormat.py
Add the name to the cells in OpenMC to improve identification. The name is the same that is used in MCNP cell.Comments, which is taken from the part names in the Step file.
In the Python input format, Cell definition will be converted from
```python
C2 = openmc.Cell(fill=M4, region=((+S6 & -S13 & -S10) | (-S12 & -S6)))
```
to
```python
C2 = openmc.Cell(name="Name of the cell in the Step file", fill=M4, region=((+S6 & -S13 & -S10) | (-S12 & -S6)))
```
XML files are also modified.
There is an automatic cell comment with several lines:
```
Automatic Generated Void Cell. Enclosure(-26.300, 26.300, -26.300, 26.300, -65.000, 31.000)
Enclosed cells : (1, 2, 3, 4, 5)
```
In this cases, the new line character is replaced by a ". ", so that line would be:
```
Automatic Generated Void Cell. …
```
=> Add the name to the cells in OpenMC to improve identification

tests/test_convert.py, tests/test_transport.py
this just changes the method of conversion from simplify fully to simplify no
this produces "better" geometry in some cases and therefore we no longer have to skip the CI testing transport for a few geometries geometries.
there remains five volumes that are not passing the CI
=> transport tests - reduced number of skipped models

tests/test_convert.py, tests/test_volumes.py
this just changes the method of conversion from simplify fully to simplify no
this produces "better" geometry in some cases and therefore we no longer have to skip the CI testing volumes for a few geometries geometries.
there remains a single volume that is not passing on the CI with the number of samples
=> volume tests - reduced number of skipped models

.gitignore
[GitHub provide a default .gitignore when making a python project repo.](https://github.com/github/gitignore/blob/main/Python.gitignore)
This PR extends the existing .gitignore to include standard python files from the github default .gitignore and adds a few other file types for openmc output files
A few of the file types we had in the existing gitignore are covered by the github one so I've also removed the tiny amount of duplication
=> added standard gitignore for python project

.github/workflows/python-publish.yml
This PR adds an action for automated pypi publishing
When a release is published then this action will make a pypi package for geouned.
Someone will have to make a pypi account and follow these steps to add a trusted publisher. 
I am happy to help maintain the pypi package over on pypi.org if that helps and also happy to jump on a teams call to walk through the process.
https://docs.pypi.org/trusted-publishers/adding-a-publisher/#:~:text=Adding%20a%20trusted%20publisher%20to%20a%20PyPI,requires%20a%20single%20setup%20step.&text=That%20link%20will%20take%20you,(such%20as%20GitHub%20Actions).
=> added pypi publish action

src/geouned/GEOReverse/Modules/MCNPinput.py, src/geouned/GEOReverse/Modules/Parser/parser.py, src/geouned/GEOReverse/Modules/Utils/BooleanSolids.py, src/geouned/GEOReverse/Modules/XMLinput.py, src/geouned/GEOReverse/Modules/splitFunction.py, src/geouned/GEOUNED/Conversion/CellDefinition.py, src/geouned/GEOUNED/Decompose/Decom_one.py, src/geouned/GEOUNED/LoadFile/LoadFunctions.py, src/geouned/GEOUNED/LoadFile/LoadSTEP.py, src/geouned/GEOUNED/Utils/BasicFunctions_part2.py, src/geouned/GEOUNED/Utils/BooleanSolids.py, src/geouned/GEOUNED/Void/VoidBoxClass.py, src/geouned/GEOUNED/Write/Functions.py, src/geouned/GEOUNED/Write/MCNPFormat.py, src/geouned/GEOUNED/Write/OpenMCFormat.py, src/geouned/GEOUNED/Write/PHITSFormat.py, src/geouned/GEOUNED/Write/SerpentFormat.py, src/geouned/GEOUNED/Write/StringFunctions.py, src/geouned/GEOUNED/__init__.py
Found a few unused variables in the code.
Perhaps best to remove them
=> Removing unused variables

src/geouned/GEOUNED/__init__.py
This PR allows users to pass in arguments directly to the GEOUNED class.
I put in type hints for the arguments I'm sure about.
fully compatible with the current way of running a config file, but just gives another way of making use of the class by directly calling it with the arguments for example this is now allowed
```
from geouned import GEOUNED
geo = GEOUNED(stepFile='example.stp', title='geouned_is_great')
```
This keeps the same default values that were previously coded and set equal to the class ```.__dict__``` attribute.
This **still allows the config.ini** file to be loaded in the same ways as before. We actually make use of the config file loading in the tests so this shows that the current config method still works
=> Geouned class init now accepts arguments

src/geouned/GEOUNED/__init__.py
This PR changes the __init__.py file so that it uses the class attributes instead of the __dict__ and key to access class attributes.
=> using self. instead of __dict__ and keyword to get class attributes

src/geouned/GEOUNED/Conversion/CellDefinition.py
This PR fixes #94. Instead of always using the minimum radius of d1 and d2, if the cell is inside of the surface it uses the maximum radius in order to ensure we do not clip the cell unnecessarily.
=> Fix to position of additional cylindrical surface used to limit torus extent

src/geouned/GEOReverse/Modules/Utils/BooleanSolids.py, src/geouned/GEOReverse/Modules/Utils/booleanFunction.py, src/geouned/GEOUNED/Utils/BooleanSolids.py, src/geouned/GEOUNED/Utils/booleanFunction.py, src/geouned/GEOUNED/Void/VoidBoxClass.py
This PR changes all the cases in the code where we compare a boolean using "==" to use "is" instead
PEP8
E712 comparison to False should be 'if cond is False:' or 'if not cond:'
E712 comparison to True should be 'if cond is True:' or 'if cond:
this reduces the pep8 warnings identified by flake8 to 662, the dev branch is currently 700
To count flake8 warnings 
```
pip install flake8
cd GEOUNED  # cd to base repo folder
flake8 --count
```
=> Using "is" instead of "==" to compare boolean values

src/geouned/GEOReverse/Modules/MCNPinput.py, src/geouned/GEOReverse/Modules/XMLinput.py, src/geouned/__init__.py
Just adding the class names instead of using the import * wild card.
This helps linters know which objects and functions are within scope of the file, saves a tiny amount of time not importing unused classes/ functions and also addresses another few pep8 (F403) complaints from flake8
for example
```
./src/geouned/GEOReverse/Modules/XMLinput.py:10:1: F403 'from .Objects import *' used; unable to detect undefined names
```
=> Specific imports instead of wild card

.github/workflows/black.yml, scripts/geounedClassCall.py, src/geouned/GEOReverse/Modules/MCNPinput.py, src/geouned/GEOUNED/Conversion/CellDefinition.py, src/geouned/GEOUNED/Utils/Geometry_GU.py, src/geouned/GEOUNED/Utils/Options/Classes.py, src/geouned/GEOUNED/Utils/Options/mcnpNumericDefault.py, src/geouned/GEOUNED/Utils/Options/optionsDefault.py, src/geouned/GEOUNED/Utils/Options/tolerancesDefault.py, src/geouned/GEOUNED/Utils/booleanFunction.py, src/geouned/GEOUNED/__init__.py, tests/test_convert.py
This PR adds a new action to the CI
The action runs black with default settings (easy for the user to reproduce)
If the code is not formatted as black would format it then the CI will fail and provide formatting comments in the CI logs
If the code would be unchanged by black then the CI passes.
This first commit should fail the new CI check (called lintr) as there has been some non PEP8 code added since I formatted the whole repo on pr #72 
I will then run ```black``` locally and the push again and the CI should pass
This is quite strict so feel free to reject this PR but I think it is one way of keeping the code formatted with PEP8 even though black style is not universally liked it can save develop time fixing spaces and indentation and simple stuff like that
=> Adding formatter to CI to keep code in PEP8

src/geouned/GEOReverse/Modules/MCNPinput.py, src/geouned/GEOReverse/Modules/Objects.py, src/geouned/GEOReverse/Modules/Parser/parser.py, src/geouned/GEOReverse/Modules/Utils/BooleanSolids.py, src/geouned/GEOReverse/Modules/Utils/booleanFunction.py, src/geouned/GEOReverse/Modules/buildCAD.py, src/geouned/GEOReverse/Modules/processInp.py, src/geouned/GEOReverse/Modules/remh.py, src/geouned/GEOReverse/Modules/splitFunction.py, src/geouned/GEOUNED/Conversion/CellDefinition.py, src/geouned/GEOUNED/Cuboid/translate.py, src/geouned/GEOUNED/Decompose/Decom_one.py, src/geouned/GEOUNED/LoadFile/LoadFunctions.py, src/geouned/GEOUNED/LoadFile/LoadSTEP.py, src/geouned/GEOUNED/Utils/BasicFunctions_part1.py, src/geouned/GEOUNED/Utils/BasicFunctions_part2.py, src/geouned/GEOUNED/Utils/BooleanSolids.py, src/geouned/GEOUNED/Utils/Functions.py, src/geouned/GEOUNED/Utils/booleanFunction.py, src/geouned/GEOUNED/Void/Void.py, src/geouned/GEOUNED/Void/voidFunctions.py, src/geouned/GEOUNED/Write/AdditionalFiles.py, src/geouned/GEOUNED/Write/Functions.py, src/geouned/GEOUNED/Write/MCNPFormat.py, src/geouned/GEOUNED/Write/OpenMCFormat.py, src/geouned/GEOUNED/Write/PHITSFormat.py, src/geouned/GEOUNED/Write/SerpentFormat.py, src/geouned/GEOUNED/__init__.py
This PR replaces all the ```.format``` methods of string manipulkation with f strings.
f strings produce the same output but are
- more readable as variable is inline
- more concise
- shorter lines 
- less lines (this PR reduces code base by 79 lines)
- faster
f strings are supported by python 3.6 and above. Seeing as the package already requests python 3.8 or above this change is compatible
=> f strings instead of .format

src/geouned/GEOReverse/Modules/Parser/parser.py, src/geouned/GEOReverse/Modules/buildCAD.py, src/geouned/GEOUNED/Void/Void.py, src/geouned/GEOUNED/Write/Functions.py, src/geouned/GEOUNED/__init__.py, tests/test_convert.py, tests/test_transport.py, tests/test_volumes.py
The conversion tests take 93 seconds locally but the majority of that is just for two of the geometries.
I think we can remove these two from the CI testing and keep them in the locally testing.
This would speed up the CI considerably as these large geometries are also the slowest for transport and volume calcs as well
Ideally we would have stp files designed to test the various different conversion challenges.
Here are all the timings for the CI test_convert script.
```
=========================================================== slowest durations ============================================================
30.04s call     tests/test_convert.py::test_conversion[input_step_file24]
24.68s call     tests/test_convert.py::test_conversion[input_step_file25]
7.97s call …
```
=> Quicker tests for ci

.github/workflows/documentation.yml
this slight change to the documentation CI means it is only triggers the final part of the action on a push to dev or main.
=> Trigger docs build on push only

src/geouned/GEOUNED/Write/Functions.py
spotted a tiny tiny missing ```=``` sign on the openmc py output
=> added missing = sign

pyproject.toml
I noticed that this file src/geouned/GEOUNED/Utils/Functions.py imports numpy but we have not got numpy in the pyprojects.
This PR adds numpy to the dependencies so that pip installing it brings in the needed dependencies
=> added missing package to dependencies

src/geouned/GEOUNED/Conversion/CellDefinition.py, src/geouned/GEOUNED/Cuboid/translate.py, src/geouned/GEOUNED/Decompose/Decom_one.py, src/geouned/GEOUNED/LoadFile/LoadFunctions.py, src/geouned/GEOUNED/LoadFile/LoadSTEP.py, src/geouned/GEOUNED/Utils/BooleanSolids.py, src/geouned/GEOUNED/Utils/Functions.py, src/geouned/GEOUNED/Utils/Geometry_GU.py, src/geouned/GEOUNED/Void/Void.py, src/geouned/GEOUNED/Write/MCNPFormat.py, src/geouned/GEOUNED/Write/PHITSFormat.py, src/geouned/GEOUNED/Write/SerpentFormat.py, src/geouned/GEOUNED/__init__.py
Some of the logger.info commands had a , in the line. This was causing the program to error when it came across those lines.
Worryingly our tests didn't catch this bug and it was reported by @akolsek when using the dev branch to translate a large model.
Glad to get it fixed but we should probably also add a few more well chosen step files to the CI. If we chose small geometries which test currently untested parts of the code that would be great. Also we should think about adding some coverage
=> Fixing logger commands

src/geouned/GEOUNED/Utils/data_classes.py
This simple PR adds standard class getters and setters to the Options, Tolerances and NumericFormat class
These check the values whenever the user sets them and checks they are the correct type and in some cases above 0
I've also changed the accepted types to Real which allows floats or ints for enlargeBox and splitTolerance  as it appears we are sometimes passing ints and sometimes passing floats to these attributes.
This will be useful in the future as we can migrate the type checking [here ](https://github.com/GEOUNED-org/GEOUNED/blob/17d4500623754d17d12b371eac818ed968cc6dd4/src/geouned/GEOUNED/__init__.py#L288-L344)with more standard way of doing type checking on class attributes.
=> Adding getters setters type checking to Options, Tolerances, NumericFormat class

docs/python_api.rst, docs/usage.rst, src/geouned/GEOUNED/Cuboid/translate.py, src/geouned/GEOUNED/LoadFile/LoadSTEP.py, src/geouned/GEOUNED/Utils/data_classes.py, src/geouned/GEOUNED/Void/Void.py, src/geouned/GEOUNED/Write/MCNPFormat.py, src/geouned/GEOUNED/Write/PHITSFormat.py, src/geouned/GEOUNED/Write/SerpentFormat.py, src/geouned/GEOUNED/Write/WriteFiles.py, src/geouned/GEOUNED/__init__.py, tests/test_convert.py
this PR introduces a settings class to hold many of the class attributes that currently go to CadToCsg
The settings class has been added to the docs in the python api section and the usage example has been updated to show how the settings is used.
I've added doc strings, type hints to the class to provide the good documentation.
I've also added getter and setter methods with some type checking to help guard against incorrect attribute assignment and inform the user when they enter the incorrect type for an attribute
=> Add settings class

docs/usage.rst, src/geouned/GEOUNED/__init__.py, tests/test_convert.py
This PR adds an export_csg method. Moving the cadtocsg class attributes that are not needed until the end of the process into the export_csg method
This allows users to redo the quick writing to csg file without redoing the computationally intense conversion of the cad
The usage section of the docs have been updated
The tests have been updated
=> Adding export csg method

src/geouned/GEOUNED/Utils/BasicFunctions_part2.py, tests/test_convert.py
Fixing issue #154 
First the PR adds a test to the CI which should fail as the bug is present
Then the 2nd commit fixes the bug and the CI including the new test should pass 🤞
=> Fixing issue 154

src/geouned/GEOUNED/Void/VoidBoxClass.py
@akolsek found a bug where the expand method is being called without a few arguments.
Sorry for missing this.
We could really do with some more CI tests that probe more of the attribute parameters
=> added missing args bug

src/geouned/GEOUNED/core.py
We call decompose a 3 times and sometimes it is to decompose solids and sometimes it is to decompose enclosures. 
As pointed out by @akolsek it  would be useful to know on the progress bar what the decompose is working on.
This PR adds a more flexible description that changes depending on the type of decompose occurring
=> added description of solid being decomposed

docs/usage/python_api_usage.rst, docs/usage/python_cli_usage.rst, scripts/config.ini, scripts/configReverse.ini, scripts/geounedClassCall.py, src/geouned/GEOReverse/reverse.py, src/geouned/GEOUNED/core.py, src/geouned/GEOUNED/write/write_files.py, tests/config_complete_defaults.json, tests/test_convert.py
When specifying an outFormat most of the codes are in lower case appart from the best one 😉 
currently we need to request openmc outputs with ```openMC_PY``` and ```openMC_XML``` which is a bit tricky to remember which letters are upper case and which are not and also inconsistent with the other codes.
This PR proposes that we change these to be lower case like the other codes
documentation has been updated
There is a nice check in the code so anyone using it will get a reasonable error message if trying the old upper case names
https://github.com/GEOUNED-org/GEOUNED/blob/6daf2e363bfa46c038c191f6a8581dfae07260b7/src/geouned/GEOUNED/write/write_files.py#L31-L35
=> openmc_py and openmc_xml lower case

src/geouned/GEOUNED/core.py
When users make use of export_csg there is no checking that the arguments are the correct type
We have type checking on all the class attributes so it is a shame not to have type checking on this method
This PR adds checks that ensure the user inputs the correct type and if not they get an informative type error message that hopefully helps them correct the input
=> Added type checking on export csg

README.md, docs/install/install_linux.rst, docs/install/install_windows.rst
Not ready to merge
The conda forge recipe is passing :tada: and subject to review could be merged in. If https://github.com/conda-forge/staged-recipes/pull/26385 gets merged then we can simplify our install instructions.
Installation becomes a one liner, if you have conda/mamba :tada:
```conda install -c conda-forge geouned```
closes #177
=> more concise install with conda-forge

src/geouned/GEOUNED/core.py
Tiny PR that reworks the path creation and checking of files exiting. Saves a few lines of code
=> Remove need for os import

README.md
the action name for the documentation has been changed so the badge needs a small update to the URL
=> Update docs badge with new action name

1.1.0/_modules/geouned/GEOUNED/core.html, 1.1.0/_modules/geouned/GEOUNED/utils/data_classes.html, 1.1.0/_modules/index.html, 1.1.0/developer_guide.html, 1.1.0/genindex.html, 1.1.0/index.html, 1.1.0/install/index.html, 1.1.0/install/install_linux.html, 1.1.0/install/install_windows.html, 1.1.0/methodology.html, 1.1.0/python_api.html, 1.1.0/search.html, 1.1.0/usage/index.html, 1.1.0/usage/python_api_usage.html, 1.1.0/usage/python_cli_usage.html
correcting the url to the version switcher json
=> manual corrected version json url

docs/developer_guide.rst
This tiny fix to the docs adds details of the merge type that should be used when PR from dev to main. We tried the rebase PR last time and somehow it missed 25 commits so we now think the "create a merge commit" is the way to go. Sorry for my mistake
=> improved documentation on release procedure, merge type for dev to main

.github/workflows/documentation_release.yml
When we release a version the default docs should get automatically updated but [this ](https://github.com/GEOUNED-org/GEOUNED/actions/runs/9561799756/workflow)action
However when releasing version 1.2.0 the default docs didn't get automatically updated.
This is the [first time](https://github.com/GEOUNED-org/GEOUNED/actions/workflows/documentation_release.yml) the action has run so it is perhaps not a total surprise 
the "Deploy to github page" stage posted this error but didn't fail
```cp: no such file or directory: /home/runner/work/GEOUNED/GEOUNED/_build//.*```
So I think changing this line
publish_dir: _build/
to
publish_dir: _build
will fix the error
I noticed the[ dev documentation updating action](https://github.com/GEOUNED-org/GEOUNED/blob/f7f42791978a5ec7589a209c73d4d8277072f879/ …
=> fixing auto update of default docs by removed trailing / in path

docs/usage/python_cadtocsg_api_usage.rst, docs/usage/python_cadtocsg_cli_usage.rst, src/geouned/GEOUNED/utils/data_classes.py, tests/config_cadtocsg_complete_defaults.json, tests/test_cadtocsg.py
The default behaviour for compSolids setting was set to True. This leads to solids in a single component being merged in the MCNP model cell definitions. The default should be false to respect the original structure tree. 
-
- [] I have added tests that prove my fix is effective or that my feature works
=> change default compSolids behaviour

src/geouned/GEOUNED/core.py
Load_step_file method was called before Settings class was updated.
Please include a summary of the changes and motivation for the changes
=> fix bug in "from_json method"

src/geouned/GEOUNED/void/void.py
locate the progress bar at the position where space division is carried out in the void building process
=> update void progress bar

src/geouned/GEOUNED/write/functions.py
Change way of writting parameters of PX, PY, PZ planes in output files. Instead of evaluating the parameter as the scalar product of the plane normal with a point on the plane, the x,y,z component of the plane is used.
This should fix some error when model dimensions are large.
=> Coefficient px,py,pz planes

src/geouned/GEOUNED/void/void_box_class.py
Bad void generation was done when sphere was used as enclosure.
=> fix bug with spherical shape enclosure

src/geouned/GEOUNED/utils/data_classes.py, tests/config_cadtocsg_non_defaults.json
Fixed the void mat instance checker to  check for the first entry being an int, second entry being a float or int, and the third entry being a str.
Please include a summary of the changes and motivation for the changes
#263
=> Fixed instance checker in voidMat

src/geouned/GEOUNED/utils/data_classes.py
=> Instance checker in void mat

docs/install/install_windows.rst
Following the current instruction, the installation of GEOUNED using Conda can sometimes take a very long time to resolve dependencies. If you have an older version of conda (23.9 or less), the default solver is very slow - it is recommended to install GEOUNED using conda-libmamba-solver, default in conda 23.10 and newer.
Solves the issue #278 
- [x ] I'm making a PR from a feature branch on my fork into GEOUNED-org/GEOUNED/dev branch
- [x ] I have followed [PEP8 style guide]([url](https://peps.python.org/pep-0008/)) for Python or run a formatter such as [black]([url](https://github.com/psf/black)) or [ruff …
=> Adding the mention of libmamba solver to installation instructions

src/geouned/GEOReverse/Modules/MCNPinput.py
Adds a return statement to `coeffs_to_points` function in `MCNPInput.py`
#292
- [N/A] I have made corresponding changes to the documentation
- [] I have added tests that prove my fix is effective or that my feature works
=> Adds return statement to points_to_coeffs

src/geouned/GEOReverse/Modules/MCNPinput.py
MCNP allows for transformation matrices that specify only 6 elements rather than all 9. GEOUNED needs to compute the last 3 in this case.
Fixes this issue: #251
=> Mcnp 6element matrix
